<?php

namespace Database\Seeders;

use App\Models\Paciente;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PacienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pacientes = [
            [
                'nome' => 'João',
                'apelido' => 'Silva',
                'data_nascimento' => '1990-05-15',
                'genero' => 'masculino',
                'celular' => '+258843456789',
                'celular_alternativo' => '+258823456789',
                'email' => 'joao.silva@email.com',
                'whatsapp' => '+258843456789',
                'estado_civil' => 'casado',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 1,
                'provincia_id' => 1,
                'distrito_id' => 1,
                'bairro_id' => 1,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Av. Julius Nyerere',
                'numero_casa' => '123',
                'quarteirao' => '5',
                'nome_familiar' => 'Maria Silva',
            ],
            [
                'nome' => 'Maria',
                'apelido' => 'Santos',
                'data_nascimento' => '1985-08-22',
                'genero' => 'feminino',
                'celular' => '+258849876543',
                'celular_alternativo' => null,
                'email' => 'maria.santos@email.com',
                'whatsapp' => '+258849876543',
                'estado_civil' => 'solteiro',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 2,
                'provincia_id' => 1,
                'distrito_id' => 2,
                'bairro_id' => 2,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Rua da Resistência',
                'numero_casa' => '456',
                'quarteirao' => '10',
                'nome_familiar' => 'Pedro Santos',
            ],
            [
                'nome' => 'Carlos',
                'apelido' => 'Mendes',
                'data_nascimento' => '1978-12-10',
                'genero' => 'masculino',
                'celular' => '+258845678901',
                'celular_alternativo' => '+258825678901',
                'email' => 'carlos.mendes@email.com',
                'whatsapp' => '+258845678901',
                'estado_civil' => 'divorciado',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 2,
                'unidade_organica_id' => 1,
                'provincia_id' => 2,
                'distrito_id' => 3,
                'bairro_id' => 3,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Av. Eduardo Mondlane',
                'numero_casa' => '789',
                'quarteirao' => '15',
                'nome_familiar' => 'Ana Mendes',
            ],
            [
                'nome' => 'Ana',
                'apelido' => 'Costa',
                'data_nascimento' => '1995-03-18',
                'genero' => 'feminino',
                'celular' => '+258842345678',
                'celular_alternativo' => null,
                'email' => null,
                'whatsapp' => '+258842345678',
                'estado_civil' => 'solteiro',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 3,
                'provincia_id' => 1,
                'distrito_id' => 1,
                'bairro_id' => 4,
                'tipo_documento_id' => 2,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Rua da Paz',
                'numero_casa' => '321',
                'quarteirao' => '8',
                'nome_familiar' => 'Teresa Costa',
            ],
            [
                'nome' => 'Pedro',
                'apelido' => 'Rodrigues',
                'data_nascimento' => '1988-07-25',
                'genero' => 'masculino',
                'celular' => '+258846789012',
                'celular_alternativo' => '+258826789012',
                'email' => 'pedro.rodrigues@email.com',
                'whatsapp' => '+258846789012',
                'estado_civil' => 'casado',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 2,
                'provincia_id' => 1,
                'distrito_id' => 2,
                'bairro_id' => 5,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Av. Samora Machel',
                'numero_casa' => '654',
                'quarteirao' => '12',
                'nome_familiar' => 'Lucia Rodrigues',
            ],
            [
                'nome' => 'Isabel',
                'apelido' => 'Fernandes',
                'data_nascimento' => '1992-11-08',
                'genero' => 'feminino',
                'celular' => '+258847890123',
                'celular_alternativo' => null,
                'email' => 'isabel.fernandes@email.com',
                'whatsapp' => '+258847890123',
                'estado_civil' => 'viuvo',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 2,
                'unidade_organica_id' => 1,
                'provincia_id' => 3,
                'distrito_id' => 4,
                'bairro_id' => 6,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Rua dos Continuadores',
                'numero_casa' => '987',
                'quarteirao' => '20',
                'nome_familiar' => 'Manuel Fernandes',
            ],
            [
                'nome' => 'Francisco',
                'apelido' => 'Almeida',
                'data_nascimento' => '1980-04-14',
                'genero' => 'masculino',
                'celular' => '+258848901234',
                'celular_alternativo' => '+258828901234',
                'email' => 'francisco.almeida@email.com',
                'whatsapp' => '+258848901234',
                'estado_civil' => 'casado',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 3,
                'provincia_id' => 1,
                'distrito_id' => 1,
                'bairro_id' => 7,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Av. 25 de Setembro',
                'numero_casa' => '147',
                'quarteirao' => '3',
                'nome_familiar' => 'Rosa Almeida',
            ],
            [
                'nome' => 'Beatriz',
                'apelido' => 'Pereira',
                'data_nascimento' => '1998-09-30',
                'genero' => 'feminino',
                'celular' => '+258849012345',
                'celular_alternativo' => null,
                'email' => null,
                'whatsapp' => '+258849012345',
                'estado_civil' => 'solteiro',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 2,
                'provincia_id' => 2,
                'distrito_id' => 5,
                'bairro_id' => 8,
                'tipo_documento_id' => 2,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Rua da Liberdade',
                'numero_casa' => '258',
                'quarteirao' => '6',
                'nome_familiar' => 'Joana Pereira',
            ],
            [
                'nome' => 'António',
                'apelido' => 'Sousa',
                'data_nascimento' => '1975-01-20',
                'genero' => 'masculino',
                'celular' => '+258840123456',
                'celular_alternativo' => '+258820123456',
                'email' => 'antonio.sousa@email.com',
                'whatsapp' => '+258840123456',
                'estado_civil' => 'divorciado',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 2,
                'unidade_organica_id' => 1,
                'provincia_id' => 1,
                'distrito_id' => 1,
                'bairro_id' => 9,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Av. Mao Tse Tung',
                'numero_casa' => '369',
                'quarteirao' => '18',
                'nome_familiar' => 'Carla Sousa',
            ],
            [
                'nome' => 'Teresa',
                'apelido' => 'Martins',
                'data_nascimento' => '1987-06-12',
                'genero' => 'feminino',
                'celular' => '+258841234567',
                'celular_alternativo' => null,
                'email' => 'teresa.martins@email.com',
                'whatsapp' => '+258841234567',
                'estado_civil' => 'casado',
                'nacionalidade' => 'moçambicana',
                'tipo_utente_id' => 1,
                'unidade_organica_id' => 3,
                'provincia_id' => 3,
                'distrito_id' => 6,
                'bairro_id' => 10,
                'tipo_documento_id' => 1,
                'raca_id' => 1,
                'avenida_rua_celula' => 'Rua da Amizade',
                'numero_casa' => '753',
                'quarteirao' => '25',
                'nome_familiar' => 'Miguel Martins',
            ],
        ];

        foreach ($pacientes as $pacienteData) {
            Paciente::create($pacienteData);
        }

        $this->command->info('✅ 10 pacientes criados com sucesso!');
    }
}
